import { UserProfile, Department, Complaint, TimelineEvent, Feedback, NotificationItem, ServiceRequest } from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Electrical & Power Maintenance',
    code: 'ELEC',
    head_name: 'Dr. R. Vijay Krishna (HOD, EEE)',
    head_email: 'vijaykrishna.r@nriit.edu.in',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-2',
    name: 'Plumbing & Civil Infrastructure',
    code: 'PLUM',
    head_name: 'Dr. G.L. Narayana (HOD, Civil)',
    head_email: 'narayana.gl@nriit.edu.in',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-3',
    name: 'IT Infrastructure & Campus Wi-Fi',
    code: 'ITINF',
    head_name: 'Dr. K.V. Sambasiva Rao (HOD, CSE)',
    head_email: 'sambasivarao.kv@nriit.edu.in',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-4',
    name: 'Sanitation & Hygiene Services',
    code: 'CLEAN',
    head_name: 'Prof. N.V. Surendra Babu (HOD, ECE)',
    head_email: 'surendrababu.nv@nriit.edu.in',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-5',
    name: 'Campus Transport & Fleet',
    code: 'TRANS',
    head_name: 'Dr. P. Rama Koteswara Rao (HOD, Mech)',
    head_email: 'ramakoteswararao.p@nriit.edu.in',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dept-6',
    name: 'Campus Vigilance & Security',
    code: 'SEC',
    head_name: 'Capt. K. Satyanarayana (Security Chief)',
    head_email: 'security.head@nriit.edu.in',
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

export const DEMO_PROFILES: Record<string, UserProfile> = {
  student: {
    id: 'usr-student-1',
    email: 'asifkhan.m@nriit.edu.in',
    full_name: 'Mohammad Asif Khan',
    role: 'student',
    student_id_number: '20KN1A0501',
    phone: '+91 98480 12345',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    created_at: '2026-01-15T09:00:00.000Z',
  },
  staff: {
    id: 'usr-staff-1',
    email: 'satyanarayana.ch@nriit.edu.in',
    full_name: 'Sri Ch. Satyanarayana (Senior Electrical Lead)',
    role: 'staff',
    department_id: 'dept-1',
    department_name: 'Electrical & Power Maintenance',
    phone: '+91 94401 99880',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    created_at: '2026-01-10T09:00:00.000Z',
  },
  admin: {
    id: 'usr-admin-1',
    email: 'sambasivarao.kv@nriit.edu.in',
    full_name: 'Dr. K.V. Sambasiva Rao (CSE Department HOD)',
    role: 'admin',
    department_id: 'dept-3',
    department_name: 'IT Infrastructure & Campus Wi-Fi',
    phone: '+91 94401 23456',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    created_at: '2026-01-05T09:00:00.000Z',
  },
  super_admin: {
    id: 'usr-superadmin-1',
    email: 'principal@nriit.edu.in',
    full_name: 'Dr. C. Naga Bhaskar (Principal & Campus Director)',
    role: 'super_admin',
    phone: '+91 94400 11223',
    avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    created_at: '2026-01-01T09:00:00.000Z',
  },
};

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const hoursAhead = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-101',
    complaint_number: 'CMP-2026-0101',
    title: 'Ceiling Fan Making Loud Noise & Sparking',
    description: 'The ceiling fan in Room 402 is vibrating heavily, sparking from the top canopy socket, and creating a fire hazard.',
    category: 'electrical',
    priority: 'emergency',
    status: 'in_progress',
    location: 'Hostel Block A, Room 402',
    student_id: 'usr-student-1',
    student_name: 'Alex Johnson',
    student_email: 'alex.johnson@demo.nriuniv.edu',
    department_id: 'dept-1',
    department_name: 'Electrical & Maintenance',
    assigned_staff_id: 'usr-staff-1',
    assigned_staff_name: 'Rajesh Kumar',
    evidence_urls: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80'
    ],
    created_at: hoursAgo(1),
    due_at: hoursAhead(1), // Emergency SLA: 2h total
    updated_at: hoursAgo(0.5),
  },
  {
    id: 'cmp-102',
    complaint_number: 'CMP-2026-0102',
    title: 'Wi-Fi Disconnecting Frequently during Online Exams',
    description: 'Hostel Wi-Fi access point AP-04 is dropping packets continuously. Signals disconnect every 5 minutes.',
    category: 'internet_wifi',
    priority: 'high',
    status: 'submitted',
    location: 'Hostel Block A, 3rd Floor',
    student_id: 'usr-student-1',
    student_name: 'Alex Johnson',
    student_email: 'alex.johnson@demo.nriuniv.edu',
    department_id: 'dept-3',
    department_name: 'IT Infrastructure & Wi-Fi',
    evidence_urls: [
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80'
    ],
    created_at: hoursAgo(2),
    due_at: hoursAhead(4), // High SLA: 6h total
    updated_at: hoursAgo(2),
  },
  {
    id: 'cmp-103',
    complaint_number: 'CMP-2026-0103',
    title: 'Water Pressure Low in 2nd Floor Washroom',
    description: 'No running water available in washroom stalls 1 and 2 since morning.',
    category: 'plumbing',
    priority: 'high',
    status: 'assigned',
    location: 'Hostel Block A, 2nd Floor',
    student_id: 'usr-student-1',
    student_name: 'Alex Johnson',
    student_email: 'alex.johnson@demo.nriuniv.edu',
    department_id: 'dept-2',
    department_name: 'Plumbing & Water Management',
    assigned_staff_id: 'usr-staff-2',
    assigned_staff_name: 'Suresh Patel',
    evidence_urls: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80'
    ],
    created_at: hoursAgo(5),
    due_at: hoursAhead(1), // High SLA: 6h total
    updated_at: hoursAgo(1),
  },
  {
    id: 'cmp-104',
    complaint_number: 'CMP-2026-0104',
    title: 'Garbage Overflowing Outside Student Canteen',
    description: 'Waste bins outside central canteen have not been emptied for 2 days causing foul smell and health hazard.',
    category: 'cleaning',
    priority: 'medium',
    status: 'resolved',
    location: 'Student Center Canteen',
    student_id: 'usr-student-2',
    student_name: 'Priya Sharma',
    student_email: 'priya.s@demo.nriuniv.edu',
    department_id: 'dept-4',
    department_name: 'Sanitation & Hygiene',
    assigned_staff_id: 'usr-staff-3',
    assigned_staff_name: 'Ramesh Naidu',
    evidence_urls: [
      'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=600&q=80'
    ],
    created_at: hoursAgo(18),
    due_at: hoursAhead(6),
    updated_at: hoursAgo(2),
    resolved_at: hoursAgo(2),
  },
  {
    id: 'cmp-105',
    complaint_number: 'CMP-2026-0105',
    title: 'Main Gate RFID Barrier Sensor Malfunction',
    description: 'Automatic vehicle boom barrier at Gate 1 is failing to read student ID cards causing traffic congestion.',
    category: 'security',
    priority: 'low',
    status: 'verified',
    location: 'Campus Main Gate 1',
    student_id: 'usr-student-3',
    student_name: 'David Chen',
    student_email: 'david.c@demo.nriuniv.edu',
    department_id: 'dept-6',
    department_name: 'Campus Security',
    evidence_urls: [],
    created_at: hoursAgo(12),
    due_at: hoursAhead(60),
    updated_at: hoursAgo(10),
  },
  {
    id: 'cmp-106',
    complaint_number: 'CMP-2026-0106',
    title: 'Repeated Power Outage in Computer Science Auditorium',
    description: 'The AC and audio system tripped twice during the keynote address. Issue was marked resolved earlier but recurred.',
    category: 'electrical',
    priority: 'emergency',
    status: 'reopened',
    location: 'CS Department Auditorium',
    student_id: 'usr-student-1',
    student_name: 'Alex Johnson',
    student_email: 'alex.johnson@demo.nriuniv.edu',
    department_id: 'dept-1',
    department_name: 'Electrical & Maintenance',
    assigned_staff_id: 'usr-staff-1',
    assigned_staff_name: 'Rajesh Kumar',
    evidence_urls: [
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80'
    ],
    created_at: hoursAgo(8),
    due_at: hoursAgo(6), // SLA Breached (2h limit exceeded)
    updated_at: hoursAgo(1),
  },
  {
    id: 'cmp-107',
    complaint_number: 'CMP-2026-0107',
    title: 'Water Pipe Burst in Hostel Block A Ground Floor',
    description: 'Major water leakage from main riser pipe near room G-12. Water spreading into corridor.',
    category: 'plumbing',
    priority: 'emergency',
    status: 'in_progress',
    location: 'Hostel Block A, Ground Floor',
    student_id: 'usr-student-2',
    student_name: 'Priya Sharma',
    student_email: 'priya.s@demo.nriuniv.edu',
    department_id: 'dept-2',
    department_name: 'Plumbing & Water Management',
    assigned_staff_id: 'usr-staff-2',
    assigned_staff_name: 'Suresh Patel',
    evidence_urls: [
      'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=600&q=80'
    ],
    created_at: hoursAgo(1.5),
    due_at: hoursAhead(0.5),
    updated_at: hoursAgo(0.5),
  },
  {
    id: 'cmp-108',
    complaint_number: 'CMP-2026-0108',
    title: 'Morning Campus Shuttle Bus Arriving 25 Mins Late',
    description: 'Route 2 bus failed to arrive at South Campus pickup point on time for 8:30 AM lectures.',
    category: 'transport',
    priority: 'medium',
    status: 'closed',
    location: 'South Campus Bus Stop',
    student_id: 'usr-student-3',
    student_name: 'David Chen',
    student_email: 'david.c@demo.nriuniv.edu',
    department_id: 'dept-5',
    department_name: 'Campus Transport Services',
    assigned_staff_id: 'usr-staff-4',
    assigned_staff_name: 'Vikram Singh',
    evidence_urls: [],
    created_at: hoursAgo(30),
    due_at: hoursAgo(6),
    updated_at: hoursAgo(12),
    resolved_at: hoursAgo(15),
    closed_at: hoursAgo(12),
  }
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 'tl-1',
    complaint_id: 'cmp-101',
    user_id: 'usr-student-1',
    user_name: 'Alex Johnson',
    user_role: 'student',
    new_status: 'submitted',
    comment: 'Complaint registered by student.',
    is_internal: false,
    created_at: hoursAgo(1),
  },
  {
    id: 'tl-2',
    complaint_id: 'cmp-101',
    user_id: 'usr-admin-1',
    user_name: 'Prof. Sarah Jenkins',
    user_role: 'admin',
    old_status: 'submitted',
    new_status: 'assigned',
    comment: 'Verified as Emergency priority fire hazard. Assigned to senior electrician Rajesh Kumar.',
    is_internal: false,
    created_at: hoursAgo(0.8),
  },
  {
    id: 'tl-3',
    complaint_id: 'cmp-101',
    user_id: 'usr-staff-1',
    user_name: 'Rajesh Kumar',
    user_role: 'staff',
    old_status: 'assigned',
    new_status: 'in_progress',
    comment: 'Dispatched to Hostel Block A room 402 with replacement capacitor and safety kit.',
    is_internal: false,
    created_at: hoursAgo(0.5),
  },
];

export const INITIAL_FEEDBACK: Feedback[] = [
  {
    id: 'fb-1',
    complaint_id: 'cmp-104',
    student_id: 'usr-student-2',
    rating: 5,
    comments: 'Sanitation team arrived within 2 hours and thoroughly cleaned the canteen perimeter. Great response!',
    is_satisfied: true,
    created_at: hoursAgo(1.8),
  },
  {
    id: 'fb-2',
    complaint_id: 'cmp-108',
    student_id: 'usr-student-3',
    rating: 4,
    comments: 'Transport department added an extra backup shuttle for morning peak hours. Satisfied.',
    is_satisfied: true,
    created_at: hoursAgo(11),
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'nt-1',
    user_id: 'usr-student-1',
    title: 'Work Order Updated',
    message: 'Your complaint CMP-2026-0101 has been set to IN PROGRESS by Rajesh Kumar.',
    link: '/complaints/cmp-101',
    type: 'info',
    is_read: false,
    created_at: hoursAgo(0.5),
  },
  {
    id: 'nt-2',
    user_id: 'usr-student-1',
    title: 'Emergency Priority Flagged',
    message: 'CMP-2026-0106 has been reopened and marked as EMERGENCY priority.',
    link: '/complaints/cmp-106',
    type: 'warning',
    is_read: false,
    created_at: hoursAgo(1),
  },
  {
    id: 'nt-3',
    user_id: 'usr-admin-1',
    title: 'SLA Breach Alert',
    message: 'Complaint CMP-2026-0106 in CS Department Auditorium has breached its 2-hour SLA deadline.',
    link: '/complaints/cmp-106',
    type: 'sla',
    is_read: false,
    created_at: hoursAgo(1.2),
  }
];

export const INITIAL_SERVICES: ServiceRequest[] = [
  {
    id: 'srv-1',
    student_id: 'usr-student-1',
    student_name: 'Alex Johnson',
    service_type: 'Seminar Hall Audio-Visual Setup',
    location: 'CS Block Auditorium',
    description: 'Requesting projector and Wireless mic configuration for Capstone Expo presentation rehearsal.',
    preferred_slot: '2026-08-22 14:00 - 16:00',
    status: 'scheduled',
    created_at: hoursAgo(5),
  },
  {
    id: 'srv-2',
    student_id: 'usr-student-1',
    student_name: 'Alex Johnson',
    service_type: 'Hostel Room Deep Sanitization',
    location: 'Hostel Block A, Room 402',
    description: 'Post-maintenance cleaning service request after ceiling fan replacement.',
    preferred_slot: '2026-08-21 10:00 - 12:00',
    status: 'pending',
    created_at: hoursAgo(1),
  }
];
